#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
      SUBDIRS = Parallel D1dB D3dB Pneb K1dB C3dB DMatrix CMatrix control lattice io ion pseudopotential utilities unitcell brillouin_zone fractional linesearch timing ewald thermostats MetaDynamics
                

          OBJ = 
                

   USES_BLAS = 

  LIB_INCLUDES = 

  LIB_DEFINES = 




include ../../config/makefile.h
include ../../config/makelib.h









