#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#
# intf and aux break on IBM SP xlhpf with optimization ... why? 
 OBJ_OPTIMIZE = \
	      	compressed_io.o \
            nwpw_message.o \
            second.o


	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS =

  LIB_DEFINES = 


include ../../../config/makefile.h
include ../../../config/makelib.h

