#
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#

 OBJ_OPTIMIZE = \
            	shake_chain.o \
            	shake_chain2.o \
            	shake_chain3.o \
		shake_analysis.o \
		molecular.o \
		pspw_molecule.o \
		pspw_atom.o \
		pspw_bond.o

	  OBJ = 

      LIBRARY = libnwpwlib.a

    USES_BLAS = molecular.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

