#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

 OBJ_OPTIMIZE = \
            v_thomasfermi.o



	  OBJ = 

      LIBRARY = libofpw.a

    USES_BLAS = v_thomasfermi.F

  LIB_DEFINES = 


include ../../../../config/makefile.h
include ../../../../config/makelib.h

