#
# $Id: GNUmakefile 19707 2010-10-29 17:59:36Z d3y133 $
#

#      SUBDIRS = pspw band nwpwlib libraryps
       SUBDIRS = nwpwlib libraryps pspw paw band ofpw

          OBJ = nwpw_input.o \
                nwpw_default.o \
                nwpw_vectors_input.o


      LIBRARY = libnwpw.a


  LIB_DEFINES =




include ../config/makefile.h
include ../config/makelib.h









