# $Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $
  LIBRARY = libetrans.a
  
  OBJ = et_calc.o et_input.o et_det.o et_2e.o et_dgefa.o  \
 et_movecs_read.o et_vectors_inp.o et_fock.o \
 et_dens_prod.o et_omega2_mult.o 
 
  USES_BLAS = et_dgefa.F
 


include ../config/makefile.h
include ../config/makelib.h

