#$Id: GNUmakefile 19708 2010-10-29 18:04:21Z d3y133 $

#   OBJ_OPTIMIZE =  transport.o 
   OBJ_OPTIMIZE =   transp_input.o

   LIBRARY = libtransport.a
 USES_BLAS = transport.F

include ../config/makefile.h
include ../config/makelib.h


