
# $Id: GNUmakefile 21430 2011-11-07 21:59:54Z d3p852 $
#
 OBJ_OPTIMIZE = \
                ofpwsd.o \
		inner_loop_ofpw.o

	  OBJ = 


      LIBRARY = libofpw.a

    USES_BLAS = ofpwsd.F inner_loop_ofpw.F chi_lmbda.f

  LIB_DEFINES =


include ../../../config/makefile.h
include ../../../config/makelib.h

